name: convenient_store_management
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.11.7
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  json_serializable: ^6.7.1
  riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.0.4
  freezed: ^2.4.2
  freezed_lint: ^0.0.1-dev+1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
